import React from 'react';
import Navbar from './Navbar';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  // Get the current user's username from your authentication system
  const username = 'JohnDoe';

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/path/to/globals.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <Navbar username={username} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
